// Argus mark as a composited RGB raster for the PDF report header.
// Generated by tools/make_icon.py; committed so the build needs no tooling.
#pragma once

namespace argus {

extern const int kArgusLogoW;
extern const int kArgusLogoH;
extern const unsigned char kArgusLogoRGB[];  // W*H*3, DeviceRGB

}  // namespace argus
