#!/usr/bin/env python3
"""Embed JetBrains Mono TTFs into a committed C++ source for the PDF exporter.

The PDF writer embeds the font as a TrueType FontFile2 so reports render in a
consistent monospace face on any machine. Rather than depend on a font file path
at runtime (the CLI runs headless in CI; the GUI hides fonts inside the .app
bundle), we bake the bytes into argus_core. Re-run only when the font changes.

Usage: python3 tools/embed_font.py
"""
import os
import struct

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RES = os.path.join(ROOT, "src", "ui", "resources")
OUT = os.path.join(ROOT, "src", "core", "export", "EmbeddedFonts.cpp")


def u16(b, o):
    return struct.unpack(">H", b[o:o + 2])[0]


def tables(data):
    n = u16(data, 4)
    out = {}
    for i in range(n):
        e = 12 + i * 16
        tag = data[e:e + 4].decode("latin1")
        off = struct.unpack(">I", data[e + 8:e + 12])[0]
        out[tag] = off
    return out


def advance_per_1000(data):
    t = tables(data)
    units = u16(data, t["head"] + 18)
    adv = u16(data, t["hmtx"] + 0)  # first glyph advance (monospace -> all equal)
    return round(adv * 1000 / units)


def emit_array(f, name, data):
    f.write("const unsigned char %s[] = {\n" % name)
    for i in range(0, len(data), 20):
        f.write("    " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    f.write("};\n")
    f.write("const unsigned int %s_len = %d;\n\n" % (name, len(data)))


def main():
    with open(os.path.join(RES, "JetBrainsMono-Regular.ttf"), "rb") as fh:
        reg = fh.read()
    with open(os.path.join(RES, "JetBrainsMono-Bold.ttf"), "rb") as fh:
        bold = fh.read()
    adv = advance_per_1000(reg)

    with open(OUT, "w") as f:
        f.write("// Generated by tools/embed_font.py - do not edit by hand.\n")
        f.write("// JetBrains Mono (SIL Open Font License 1.1) embedded for the PDF exporter.\n")
        f.write('#include "EmbeddedFonts.h"\n\n')
        f.write("namespace argus {\n\n")
        emit_array(f, "kJetBrainsMonoRegular", reg)
        emit_array(f, "kJetBrainsMonoBold", bold)
        f.write("const int kJetBrainsMonoAdvance = %d;  // per 1000 em units\n\n" % adv)
        f.write("}  // namespace argus\n")
    print("wrote", OUT, "(advance/1000 =", adv, ")")


if __name__ == "__main__":
    main()
